name: patternedinput
description: A customizable Flutter widget for pattern-driven input fields with intelligent paste handling, auto-navigation, and validation. Perfect for OTP, form codes, and structured data entry.
version: 1.0.1
homepage: https://github.com/tmplabs/patternedInput

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

topics:
  - input
  - otp
  - form
  - widget
  - ui